spring:
  application:
    name: feedservice

  security:
    authentication:
      jwt:
        validity: 6000000
        secret: ab9ae52e116f4ca0d2415c75d23775fad043c1bb5774298ee1e0f34390ff09a76fe2169d16727e510046288ca913ce80

  main:
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 7379
    pool:
      min-idle: 5

  datasource:
    write:
      url: jdbc:mysql://10.1.6.16/octopusallinone-dev
      username: gaming
      password: '{cipher}b0b07b785eed98cb3fab5de48dde71eeee559935a27d06293691de8a0bfa600b'
      driverClassName: com.mysql.cj.jdbc.Driver
      maxPoolsize: 2
      leakDetectionDuration: 60000
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 60000
        max-lifetime: 1800000
        leak-detection-threshold: 20000
        validation-timeout: 5000
        keepalive-time: 30000
        pool-name: DrawWriteHikariConnPool

    read:
      url: jdbc:mysql://10.1.6.16/octopusallinone-dev
      username: gaming
      password: '{cipher}b0b07b785eed98cb3fab5de48dde71eeee559935a27d06293691de8a0bfa600b'
      driverClassName: com.mysql.cj.jdbc.Driver
      maxPoolsize: 2
      leakDetectionDuration: 60000
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        connection-timeout: 30000
        idle-timeout: 60000
        max-lifetime: 1800000
        leak-detection-threshold: 20000
        validation-timeout: 5000
        keepalive-time: 30000
        pool-name: DrawReadHikariConnPool

    hikari:
      connection-test-query: SELECT 1

    tomcat:
      max-active: 2000
      minEvictableIdleTimeMillis: 5000
      validationQuery: SELECT 1
      minIdle: 1
      maxIdle: 5
      initialSize: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 7001
  max-http-request-header-size: 100KB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7083/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
