spring.application.name=opasService

spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true
spring.main.lazy-initialization=true
server.port=7000
server.max-http-request-header-size=100KB
server.maxHttpHeaderSize=60000
management.address=localhost
logging.level.org.springframework.boot.autoconfigure=DEBUG

playerDataLocation=/home/gaming/PlayerData/
image=Image
kyc=KYC
mpesaProdsetup=false
playerBlockFeature=true
enableFreeBet=true
razorPayScheduler=false
callbackURL=https://ditest.diipl.in:8000/opas/Payment/chapa/callback
redirectwebURL=https://chewata.diipl.in
redirectmobileURL=https://chewatamobile.diipl.in
eKyc=true
eKycUrl=https://signzy.tech/
eKycImageUrl=https://persist.signzy.tech/api/files/upload
url=http://10.1.7.137:8000/opas
emailId=gamingsupport@diipl.com
emailVerficationUrl=https://goaapi.dusanegaming.com:8443/op/opas/register/email/activate
panCardAuthKey=k5GTzfOOM0UETe3NptWXMP0MJpuU4lnP
ekycUrkV3=https://api-preproduction.signzy.app/api/v3/panextensive
justCollectStatusUrl=https://getstatus-buub3ffzia-el.a.run.app
diApiUrl=https://api-uat-dus-4355h.ggglottery.com:8443
iscartBetAmt=true
isMultipleSessionLogin=true
kycEnabled=false

clientId=39610639-0b60-4511-a8ec-4b3efc4a45b7
clientSecret={cipher}f35ce0c6da79425c3ee47f4be5d59c605c7255a9323242555689432a1d8e74f9b618d1ad5c1d8fd36824cb3ab5fed65c973a751dff0900f9859be486be6b122db75dd612d079e6cfa008cdadb99daeebeaa09fe0d041c01d08c448f7888ead3459accb1c764df93b602f5c805d1231069136f43fe7c2607358dc57a4c94ed94e
thirdPartyTokenUrl=https://qa-api.ggglottery.com/api

spring.datasource.url=jdbc:mysql://10.1.6.16/octopusallinone-dev
spring.datasource.username=gaming
spring.datasource.password={cipher}f78b67127b8a025cc94c9e8a8c1ecb320cfef9247ede23bf90dc1688d931988a
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-test-query=SELECT 1

spring.datasource.write.url=jdbc:mysql://10.1.6.16/octopusallinone-dev
spring.datasource.write.username=gaming
spring.datasource.write.password={cipher}f78b67127b8a025cc94c9e8a8c1ecb320cfef9247ede23bf90dc1688d931988a
spring.datasource.write.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.write.maxPoolsize=2
spring.datasource.write.leakDetectionDuration=60000
spring.datasource.write.hikari.maximum-pool-size=20
spring.datasource.write.hikari.minimum-idle=10
spring.datasource.write.hikari.connection-timeout=30000
spring.datasource.write.hikari.idle-timeout=600000
spring.datasource.write.hikari.max-lifetime=1800000
spring.datasource.write.hikari.leak-detection-threshold=20000
spring.datasource.write.hikari.validation-timeout=5000
spring.datasource.write.hikari.keepalive-time=30000
spring.datasource.write.hikari.pool-name=OpasWriteHikariPool

spring.datasource.read.url=jdbc:mysql://10.1.6.16/octopusallinone-dev
spring.datasource.read.username=gaming
spring.datasource.read.password={cipher}f78b67127b8a025cc94c9e8a8c1ecb320cfef9247ede23bf90dc1688d931988a
spring.datasource.read.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.read.maxPoolsize=2
spring.datasource.read.leakDetectionDuration=60000
spring.datasource.read.hikari.maximum-pool-size=20
spring.datasource.read.hikari.minimum-idle=10
spring.datasource.read.hikari.connection-timeout=30000
spring.datasource.read.hikari.idle-timeout=60000
spring.datasource.read.hikari.max-lifetime=1800000
spring.datasource.read.hikari.leak-detection-threshold=20000
spring.datasource.read.hikari.validation-timeout=5000
spring.datasource.read.hikari.keepalive-time=30000
spring.datasource.read.hikari.pool-name=OpasReadHikariPool

spring.seconderydatasource.url=jdbc:mysql://10.1.6.16/octopusallinone-dev
spring.seconderydatasource.username=gaming
spring.seconderydatasource.password={cipher}f78b67127b8a025cc94c9e8a8c1ecb320cfef9247ede23bf90dc1688d931988a
spring.seconderydatasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.show-sql=false

spring.datasource.tomcat.max-active=2000
spring.datasource.tomcat.minEvictableIdleTimeMillis=5000
spring.datasource.tomcat.validationQuery=SELECT 1
spring.datasource.tomcat.minIdle=1
spring.datasource.tomcat.maxIdle=5
spring.datasource.tomcat.initialSize=1

spring.http.multipart.location=/data/upload_tmp

security.enable-csrf=false
security.require-ssl=false
server.ssl.enabled=false

spring.redis.host=localhost
spring.redis.port=7379
spring.redis.pool.min-idle=10

eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://localhost:7083/eureka/
eureka.instance.hostname=172.31.8.27
eureka.instance.leaseRenewalIntervalInSeconds=1
eureka.instance.leaseExpirationDurationInSeconds=2

isTestSetUp=true
phoneNumber=224666779459

IMAGE.BUCKET.LOCATION=D://Projects//4//data
IMAGE.BUCKET.URL=https://skillgamesstorage.diipl.in

isCashFreeProdEnvironment=true
statusUrls=https://api.cashfree.com/pg/orders
